name: Deploy JupyterLite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install -U jupyterlite-core
        python -m pip install jupyter_server
        python -m pip install jupyterlab
    - name: Build JupyterLite
      run: |
        jupyter lite build
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./_output
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2